production:
  rta :
    -
      host: localhost
      port: 5000
    -
      host: localhost
      port: 5001

  ral :
    -
      host: localhost
      port: 5002
    -
      host: localhost
      port: 5003

  bdc :
    -
      host: localhost
      port: 5004
    -
      host: localhost
      port: 5005

  sf2 :
    -
      host: localhost
      port: 5006
    -
      host: localhost
      port: 5007

development:
  rta :
    -
      host: ral.boulder.ibm.com
      port: 3781
    -
      host: ral.boulder.ibm.com
      port: 3782

  ral :
    -
      host: ral.boulder.ibm.com
      port: 3181
    -
      host: ral.boulder.ibm.com
      port: 3182

  bdc :
    -
      host: sf2.pok.ibm.com
      port: 3381
    -
      host: sf2.pok.ibm.com
      port: 3382

  sf2 :
    -
      host: sf2.pok.ibm.com
      port: 3581
    -
      host: sf2.pok.ibm.com
      port: 3582

#
# The following is an except from Retain News specifying the test
# nodes for SDI
#
# The following information is provided for those clients performing
# testing on the APPLTEST sustems only. The IP addresses are the same.
# Node__S/H__Port#__Driver____Listnr__Description
# RTA S 3701 APPLBCRD TCP1 TEST Primary for RTA SDI
# RTA S 3702 APPLBCRD TCP2 TEST Alternate for RTA SDI
# RTA S 6701 APPLBCRD LS01 TEST Backup Primary for RTA SDI
# RTA S 6702 APPLBCRD LS02 TEST Backup Alternate for RTA SDI
# RTA S 6709 APPLBCRD LSX1 TEST IBMLink 2000 secure access only
# RAL H 3101 APPLACRD TCP1 TEST for URSF only (no SDI)
# RAL H 3102 APPLACRD TCP2 TEST Primary for RAL SDI
# RAL H 6101 APPLACRD LS01 TEST Backup Primary for RAL SDI
# RAL H 6102 APPLACRD LS02 TEST Backup Alternate for RAL SDI
# RAL H 6109 APPLACRD LSX1 TEST IBMLink 2000 secure access
# BDC S 3301 APPLBCRD TCP1 TEST Primary for BDC SDI
# BDC S 3302 APPLBCRD TCP2 TEST Alternate for BDC SDI
# BDC S 6301 APPLBCRD LS01 TEST Backup Primary for BDC SDI
# BDC S 6302 APPLBCRD LS02 TEST Backup Alternate for BDC SDI
# BDC S 6309 APPLBCRD LSX1 TEST IBMLink 2000 secure access
# SF2 H 3501 APPLACRD TCP1 TEST Primary for SF2 SDI
# SF2 H 3502 APPLACRD TCP2 TEST Alternate for SF2 SDI
# SF2 H 6501 APPLACRD LS01 TEST Backup Primary for SF2 SDI
# SF2 H 6502 APPLACRD LS02 TEST Backup Alternate for SF2 SDI
# SF2 H 6509 APPLACRD LSX1 TEST IBMLink 2000 secure access only
# RS3 H 6201 APPLACRD UTCP TEST SDI Primary for RS3
# RS4 H 7301 APPLBCRD UTCP TEST SDI Primary for RS4

test:
  rta :
    -
      host: ral.boulder.ibm.com
      port: 3701
    -
      host: ral.boulder.ibm.com
      port: 3702

  ral :
    -
      host: ral.boulder.ibm.com
      port: 3101
    -
      host: ral.boulder.ibm.com
      port: 3102

  bdc :
    -
      host: sf2.pok.ibm.com
      port: 3301
    -
      host: sf2.pok.ibm.com
      port: 3302

  sf2 :
    -
      host: sf2.pok.ibm.com
      port: 3501
    -
      host: sf2.pok.ibm.com
      port: 3502

