development:
  host: bluepages.boulder.ibm.com
  port: 389
  base: o=ibm.com
  # base: ou=bluepages,o=ibm.com
  # port: 636
  # method: :ssl
  # bind_dn: cn=admin,dc=local,dc=net
  # password: secret

staging:
  host: bluepages.boulder.ibm.com
  port: 389
  base: o=ibm.com
  # port: 636
  # method: :ssl
  # bind_dn: cn=admin,dc=local,dc=net
  # password: secret

test:
  host: bluepages.boulder.ibm.com
  port: 389
  base: o=ibm.com
  # port: 636
  # method: :ssl
  # bind_dn: cn=admin,dc=local,dc=net
  # password: secret

production:
  host: localhost
  port: 5389
  base: o=ibm.com
  # host: bluepages.boulder.ibm.com
  # port: 389
  # port: 636
  # method: :ssl
  # bind_dn: cn=admin,dc=local,dc=net
  # password: secret
