
rta :
  -
    host: ral.boulder.ibm.com
    port: 3781
  -
    host: ral.boulder.ibm.com
    port: 3782

ral :
  -
    host: ral.boulder.ibm.com
    port: 3181
  -
    host: ral.boulder.ibm.com
    port: 3182

bdc :
  -
    host: sf2.pok.ibm.com
    port: 3381
  -
    host: sf2.pok.ibm.com
    port: 3382

sf2 :
  -
    host: sf2.pok.ibm.com
    port: 3581
  -
    host: sf2.pok.ibm.com
    port: 3582
