#!/bin/sh

if [ $# -ne 1 ] ; then
   echo "Usage: $( basename $0 ) <development|production>" 1>&2
   exit 1
fi

for i in cached_queues cached_calls cached_pmrs cached_text_lines ; do
    echo "delete from $i;"
done | psql raptor_$1
