#!/bin/bash

cd log
rm -f development-05.log
[[ -f development-04.log ]] && mv development-04.log development-05.log
[[ -f development-03.log ]] && mv development-03.log development-04.log
[[ -f development-02.log ]] && mv development-02.log development-03.log
[[ -f development-01.log ]] && mv development-01.log development-02.log
cp development.log development-01.log
cp /dev/null development.log
