#!/usr/bin/env bash

f=$( echo ~/Desktop/CSPO*.xls )
if [[ ! -r "$f" ]] ; then
  f=$( echo ~/Desktop/CSPO*.xlsx )
fi
if [[ ! -r "$f" ]] ; then
  echo "Can't find the CSPO file" 1>& 2
  exit 1
fi
git checkout master && tools/do-cspo "$f" && git checkout p51-production
